# https://artifacthub.io/packages/helm/bitnami/metallb
# https://oneuptime.com/blog/post/2025-12-06-install-metallb-with-helm-bare-metal/view
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: metallb-system
