# installation source
rke2InstallScriptUrl: https://get.rke2.io
rke2Version: "v1.36.4+rke2r1"

rke2ConfigDir: /etc/rancher/rke2
rke2ConfigFile: /etc/rancher/rke2/config.yaml
rke2ApiPort: 6443
rke2KubeconfigMode: "0644"

rke2BootstrapHost: "{{ groups['k8s_control'][0] }}"

# registration
rke2RegistrationAddress: "{{ hostvars[groups['k8s_lb'][0]].ansible_host }}"
rke2RegistrationPort: 9345

# proxy
haproxyBalanceMethod: roundrobin
