# installation source
k3s_version: "v1.37.0+k3s1"

k3s_server: "{{ hostvars[groups['k8s_control'][0]].ansible_host }}"

kubeconfig_context: "homelab-1"

tls_san_vip_dns: "k8s-prod-1.home.sauers.link"
tls_san_vip: "10.50.0.10"
