ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik-dashboard.k8s-prod-1.home.sauers.link`)
    entryPoints:
      - web
      - websecure
providers:
  kubernetesGateway:
    enabled: true
gateway:
  listeners:
    web:
      namespacePolicy:
        from: All
ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
