# applications, docker compose; managed by Dockhand on debian-01 via hawser
data_ip: "{{ debian02_data_ip }}"
mgmt_ip: "{{ debian02_mgmt_ip }}"
compose_services:
  - hawser
nfs_mounts:
  # Paperless-ngx data & media (same folder) & consume
  - src: "{{ truenas_data_ip }}:/mnt/pool1_SeagateHDDs/applications/paperless-ngx/"
    path: /mnt/paperless-ngx/
  # Jellyfin readonly AUDIO
  - src: "{{ truenas_data_ip }}:/mnt/pool1_SeagateHDDs/data/audio"
    path: /mnt/media/audio/
  # Jellyfin readonly DOCS
  - src: "{{ truenas_data_ip }}:/mnt/pool1_SeagateHDDs/data/documents"
    path: /mnt/media/documents
  # Jellyfin readonly IMG
  - src: "{{ truenas_data_ip }}:/mnt/pool1_SeagateHDDs/data/images"
    path: /mnt/media/images
  # Jellyfin readonly VID
  - src: "{{ truenas_data_ip }}:/mnt/pool1_SeagateHDDs/data/video"
    path: /mnt/media/video
