---
# Static inventory. Must be kept in sync with the tofu/vm_*.tf definitions
all: # Metagroup. Organizes multiple groups.
  children:
    linux:
      children:
        bare_hosts: # bare systemd services
          hosts: {}

        truenas_s3:
          hosts:
            lxc-1:
              ansible_host: "{{ lxc_s3_1 }}"

        docker_hosts: # docker VMs
          hosts:
            debian-01:
              ansible_host: "{{ debian01_ip }}" # DBs, Secrets
            debian-02:
              ansible_host: "{{ debian02_ip }}" # applications

        k8s_cluster:
          children:
            k8s_control: # K3s servers
              hosts:
                k8s-02:
                  ansible_host: "{{ debian03_ip }}"
            k8s_worker: # K3s agents
              hosts:
                k8s-03:
                  ansible_host: "{{ debian04_ip }}"
                k8s-04:
                  ansible_host: "{{ debian05_ip }}"
                k8s-05:
                  ansible_host: "{{ debian06_ip }}"

    # Provisioned by tofu, but hand-managed.
    windows:
      hosts: {}
