---
# Static inventory. Must be kept in sync with the tofu/vm_*.tf definitions
all: # Metagroup. Organizes multiple groups.
  children:
    linux:
      children:

        bare_hosts: # bare systemd services
          hosts: {}

        docker_hosts: # docker VMs
          hosts:
            debian-01:
              ansible_host: "{{ debian01_ip }}"
            debian-02:
              ansible_host: "{{ debian02_ip }}"

        k8s_cluster:
          # Based on:
          # - https://www.ionos.de/digitalguide/server/konfiguration/kubernetes-cluster-auf-proxmox/#content-schritt-8-netzwerk-cni-und-loadbalancer-installieren
          # - https://medium.com/@frunzasamuel/basic-rke2-setup-via-ansible-0c6a66de9be8
          children:
            k8s_lb: # load balancer for control plane HA setup
              hosts:
                k8s-01:
                  ansible_host: "{{ debian06_ip }}"
            k8s_control: # RKE2 servers
              hosts:
                k8s-02:
                  ansible_host: "{{ debian03_ip }}"
            k8s_worker: # RKE2 agents
              hosts:
                k8s-03:
                  ansible_host: "{{ debian04_ip }}"
                k8s-04:
                  ansible_host: "{{ debian05_ip }}"
                k8s-05:
                  ansible_host: "{{ debian07_ip }}"

    # Provisioned by tofu, but hand-managed.
    windows:
      hosts: {}
