---
- name: Baseline for all Kubernetes hosts
  hosts: k8s_cluster
  become: true
  roles:
    - k8s_base
#  tasks:
#    - name: Example task
#      ansible.builtin.debug: # one module (unit of code or binary)
#        msg: Hello world!
