---
- name: Configure HAProxy for the Control Plane
  hosts: k8s_lb
  become: true
  roles:
    - k8s_base
  gather_facts: true
  vars_prompt: # todo: replave with external secrets management
    - name: rke2Token
      prompt: "RKE2 cluster token (leave empty to abort)"
      private: true
      confirm: true
      unsafe: true
  tasks:
    - name: Install haproxy
      ansible.builtin.apt:
        name: haproxy
        state: present
        update_cache: true

    - name: Build HAProxy backend server list
      set_fact:
        haproxyServers: |
          {% for host in groups['k8s_control'] %}
          server {{ host | replace('.', '-') }} {{ hostvars[host].ansible_host | default(host) }}:{{ rke2RegistrationPort }} check
          {% endfor %}

    - name: Build HAProxy backend API list
      set_fact:
        haproxyApiServers: |
          {% for host in groups['k8s_control'] %}
          server {{ host | replace('.', '-') }} {{ hostvars[host].ansible_host | default(host) }}:{{ rke2ApiPort }} check
          {% endfor %}

    - name: Write haproxy configuration
      copy:
        dest: /etc/haproxy/haproxy.cfg
        mode: "0644"
        content: |
          global
            daemon
            maxconn 2048

          defaults
            mode tcp
            timeout connect 10s
            timeout client 1m
            timeout server 1m

          frontend rke2_registration
            bind *:{{ rke2RegistrationPort }}
            default_backend rke2_registration_backend

          backend rke2_registration_backend
            balance {{ haproxyBalanceMethod }}
            option tcp-check
            {{ haproxyServers }}

          frontend kube_api
            bind *:{{ rke2ApiPort }}
            default_backend kube_api_backend

          backend kube_api_backend
            balance {{ haproxyBalanceMethod }}
            option tcp-check
            {{ haproxyApiServers }}
      notify: restart haproxy

    - name: Ensure haproxy is running
      systemd:
        name: haproxy
        enabled: true
        state: started

  handlers:
    - name: restart haproxy
      systemd:
        name: haproxy
        state: restarted
