---
- name: Setup for Kubernetes Worker Nodes
  hosts: k8s_worker
  become: true
  roles:
    - k8s_base
  gather_facts: true
  vars_prompt: # todo: replave with external secrets management
    - name: rke2Token
      prompt: "RKE2 cluster token (leave empty to abort)"
      private: true
      confirm: true
      unsafe: true
  tasks:
    - name: Ensure config directory exists
      file:
        path: "{{ rke2ConfigDir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: Install RKE2 agent
      shell: curl -sfL {{ rke2InstallScriptUrl }} | INSTALL_RKE2_TYPE=agent INSTALL_RKE2_VERSION={{ rke2Version }} sh -
      args:
        creates: /usr/local/bin/rke2
    - name: Write agent config
      copy:
        dest: "{{ rke2ConfigFile }}"
        owner: root
        group: root
        mode: "0600"
        content: |
          server: https://{{ rke2RegistrationAddress }}:{{ rke2RegistrationPort }}
          token: {{ rke2Token }}
      notify: restart rke2-agent
    - name: Ensure rke2-agent is enabled and started
      systemd:
        name: rke2-agent
        enabled: true
        state: started

  handlers:
    - name: restart rke2-agent
      systemd:
        name: rke2-agent
        state: restarted
