---
- name: Setup for Kubernetes Worker Nodes
  hosts: k8s_worker
  become: true
  roles:
    - k8s_base
  gather_facts: true
  tasks:
    - name: Run k3sup (agent)
      ansible.builtin.shell: |
        k3sup join \
          --ip {{ hostvars[inventory_hostname]['ansible_host'] }} \
          --server-ip {{k3s_server}} \
          --user {{ansible_user}} \
          --k3s-version {{k3s_version}} \
          --k3s-channel stable
      delegate_to: localhost
      become: false
