---
# See https://docs.k3s.io/security/hardening-guide#ensure-protect-kernel-defaults-is-set
- name: Copy kernel parameters for kubelet
  ansible.builtin.copy:
    src: 90-kubelet.conf
    dest: /etc/sysctl.d/90-kubelet.conf
    owner: root
    group: root
    mode: "0644"
  notify: Apply kernel parameters

- name: Flush handlers to apply kernel parameters before K3s starts
  ansible.builtin.meta: flush_handlers

- name: Create K3s config drop-in dir
  ansible.builtin.file:
    path: /etc/rancher/k3s/config.yaml.d
    state: directory
    owner: root
    group: root
    mode: "0755"

# See https://docs.k3s.io/security/hardening-guide#configuration-for-kubernetes-components
- name: Copy kubelet hardening config
  ansible.builtin.copy:
    src: 90-hardening.yaml
    dest: /etc/rancher/k3s/config.yaml.d/90-hardening.yaml
    owner: root
    group: root
    mode: "0600"
  notify: Restart k3s
