---
# Install with: just deps
collections:
  - name: community.general
  - name: community.docker
  - name: ansible.posix
  - name: community.crypto # hawser TLS certificates
#  - name: infisical.vault
