# https://artifacthub.io/packages/helm/bitnami/metallb
# https://oneuptime.com/blog/post/2025-12-06-install-metallb-with-helm-bare-metal/view
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: baremetal-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.50.2.0-10.50.2.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: baremetal-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - baremetal-pool # Advertise this pool via ARP on the local network segment
